version: '3.8'
services:
  planner-vacation:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    image: planner-vacation:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped